// Canonical list of every command contributed by the Dance VS Code extension.
// Source: https://github.com/71/dance package.json contributes.commands.
// Updated against the published manifest as of 2026-05.
//
// Each entry maps the Dance command id to:
//   - title: the human-readable VS Code command palette title
//   - kak: the closest Kakoune action id (may be undefined for Dance-only ops)
//   - default: the default Kak keystroke (canonical, qwerty), used when the
//     user has not bound the command and we fall back to the canonical hint.

export interface DanceCommand {
  id: string;
  title: string;
  kak?: string;
  default?: string;
  category?: DanceCategory;
}

export type DanceCategory =
  | "core"
  | "modes"
  | "edit"
  | "history"
  | "search"
  | "seek"
  | "select"
  | "selections"
  | "view"
  | "dev";

export const DANCE_COMMANDS: readonly DanceCommand[] = [
  // ── core ────────────────────────────────────────────────────────────────
  { id: "dance.cancel", title: "Cancel Dance operation", category: "core" },
  { id: "dance.changeInput", title: "Change current input", category: "core" },
  {
    id: "dance.ifEmpty",
    title: "Execute one of two commands depending on selection emptiness",
    category: "core",
  },
  { id: "dance.ignore", title: "Ignore key", category: "core" },
  { id: "dance.openMenu", title: "Open menu", category: "core" },
  { id: "dance.run", title: "Run code", category: "core" },
  {
    id: "dance.selectRegister",
    title: "Select register for next command",
    kak: "kak.normal.register.select",
    default: '"',
    category: "core",
  },
  { id: "dance.updateCount", title: "Update Dance count", category: "core" },
  { id: "dance.updateRegister", title: "Update register contents", category: "core" },

  // ── modes ───────────────────────────────────────────────────────────────
  {
    id: "dance.modes.set",
    title: "Set Dance mode",
    category: "modes",
  },
  {
    id: "dance.modes.set.normal",
    title: "Set mode to Normal",
    kak: "kak.normal.mode.normal",
    default: "<esc>",
    category: "modes",
  },
  {
    id: "dance.modes.set.insert",
    title: "Set mode to Insert",
    kak: "kak.normal.mode.insert",
    default: "i",
    category: "modes",
  },
  {
    id: "dance.modes.set.select",
    title: "Set mode to Select",
    category: "modes",
  },
  {
    id: "dance.modes.set.temporarily",
    title: "Set Dance mode temporarily",
    category: "modes",
  },
  {
    id: "dance.modes.set.temporarily.insert",
    title: "Temporary Insert mode",
    category: "modes",
  },
  {
    id: "dance.modes.set.temporarily.normal",
    title: "Temporary Normal mode",
    kak: "kak.insert.escape-once",
    default: "<a-;>",
    category: "modes",
  },
  {
    id: "dance.modes.insert.before",
    title: "Insert before",
    kak: "kak.normal.insert.before",
    default: "i",
    category: "modes",
  },
  {
    id: "dance.modes.insert.after",
    title: "Insert after",
    kak: "kak.normal.insert.after",
    default: "a",
    category: "modes",
  },
  {
    id: "dance.modes.insert.lineStart",
    title: "Insert at line start",
    kak: "kak.normal.insert.lineStart",
    default: "I",
    category: "modes",
  },
  {
    id: "dance.modes.insert.lineEnd",
    title: "Insert at line end",
    kak: "kak.normal.insert.lineEnd",
    default: "A",
    category: "modes",
  },

  // ── edit ────────────────────────────────────────────────────────────────
  {
    id: "dance.edit.align",
    title: "Align selections",
    kak: "kak.normal.edit.align",
    default: "&",
    category: "edit",
  },
  {
    id: "dance.edit.case.swap",
    title: "Swap case",
    kak: "kak.normal.edit.case.swap",
    default: "<a-`>",
    category: "edit",
  },
  {
    id: "dance.edit.case.toLower",
    title: "Transform to lower case",
    kak: "kak.normal.edit.case.lower",
    default: "`",
    category: "edit",
  },
  {
    id: "dance.edit.case.toUpper",
    title: "Transform to upper case",
    kak: "kak.normal.edit.case.upper",
    default: "~",
    category: "edit",
  },
  {
    id: "dance.edit.copyIndentation",
    title: "Copy indentation",
    kak: "kak.normal.edit.copyIndent",
    default: "<a-&>",
    category: "edit",
  },
  {
    id: "dance.edit.deindent",
    title: "Deindent selected lines",
    kak: "kak.normal.edit.deindent",
    default: "<a-<>",
    category: "edit",
  },
  {
    id: "dance.edit.deindent.withIncomplete",
    title: "Deindent (including incomplete indent)",
    kak: "kak.normal.edit.deindent.full",
    default: "<",
    category: "edit",
  },
  {
    id: "dance.edit.delete",
    title: "Delete selection",
    kak: "kak.normal.edit.delete",
    default: "<a-d>",
    category: "edit",
  },
  {
    id: "dance.edit.delete-insert",
    title: "Delete and switch to Insert",
    kak: "kak.normal.edit.delete.insert",
    default: "<a-c>",
    category: "edit",
  },
  {
    id: "dance.edit.indent",
    title: "Indent selected lines",
    kak: "kak.normal.edit.indent",
    default: ">",
    category: "edit",
  },
  {
    id: "dance.edit.indent.withEmpty",
    title: "Indent (including empty lines)",
    kak: "kak.normal.edit.indent.full",
    default: "<a->>",
    category: "edit",
  },
  {
    id: "dance.edit.insert",
    title: "Insert contents of register",
    category: "edit",
  },
  {
    id: "dance.edit.join",
    title: "Join lines",
    kak: "kak.normal.edit.join",
    default: "<a-j>",
    category: "edit",
  },
  {
    id: "dance.edit.join.select",
    title: "Join lines and select inserted spaces",
    kak: "kak.normal.edit.join.select",
    default: "<a-J>",
    category: "edit",
  },
  {
    id: "dance.edit.newLine.above",
    title: "Insert new line above",
    kak: "kak.normal.edit.newLine.above",
    default: "<a-O>",
    category: "edit",
  },
  {
    id: "dance.edit.newLine.above.insert",
    title: "Insert new line above and switch to insert",
    kak: "kak.normal.edit.newLine.above.insert",
    default: "O",
    category: "edit",
  },
  {
    id: "dance.edit.newLine.below",
    title: "Insert new line below",
    kak: "kak.normal.edit.newLine.below",
    default: "<a-o>",
    category: "edit",
  },
  {
    id: "dance.edit.newLine.below.insert",
    title: "Insert new line below and switch to insert",
    kak: "kak.normal.edit.newLine.below.insert",
    default: "o",
    category: "edit",
  },
  {
    id: "dance.edit.paste.after",
    title: "Paste after",
    kak: "kak.normal.edit.paste.after",
    default: "p",
    category: "edit",
  },
  {
    id: "dance.edit.paste.after.select",
    title: "Paste after and select",
    category: "edit",
  },
  {
    id: "dance.edit.paste.before",
    title: "Paste before",
    kak: "kak.normal.edit.paste.before",
    default: "P",
    category: "edit",
  },
  {
    id: "dance.edit.paste.before.select",
    title: "Paste before and select",
    category: "edit",
  },
  {
    id: "dance.edit.pasteAll.after",
    title: "Paste all after",
    kak: "kak.normal.edit.pasteAll.after",
    default: "<a-p>",
    category: "edit",
  },
  {
    id: "dance.edit.pasteAll.after.select",
    title: "Paste all after and select",
    category: "edit",
  },
  {
    id: "dance.edit.pasteAll.before",
    title: "Paste all before",
    kak: "kak.normal.edit.pasteAll.before",
    default: "<a-P>",
    category: "edit",
  },
  {
    id: "dance.edit.pasteAll.before.select",
    title: "Paste all before and select",
    category: "edit",
  },
  {
    id: "dance.edit.replaceCharacters",
    title: "Replace characters",
    kak: "kak.normal.edit.replace",
    default: "r",
    category: "edit",
  },
  {
    id: "dance.edit.selectRegister-insert",
    title: "Pick register and replace",
    category: "edit",
  },
  {
    id: "dance.edit.yank-delete",
    title: "Copy and delete",
    kak: "kak.normal.edit.yank.delete",
    default: "d",
    category: "edit",
  },
  {
    id: "dance.edit.yank-delete-insert",
    title: "Copy, delete and switch to Insert",
    kak: "kak.normal.edit.yank.delete.insert",
    default: "c",
    category: "edit",
  },
  {
    id: "dance.edit.yank-replace",
    title: "Copy and replace (with yanked)",
    kak: "kak.normal.edit.yank.replace",
    default: "R",
    category: "edit",
  },

  // ── history ─────────────────────────────────────────────────────────────
  {
    id: "dance.history.recording.play",
    title: "Replay recording",
    kak: "kak.normal.macro.play",
    default: "Q",
    category: "history",
  },
  {
    id: "dance.history.recording.start",
    title: "Start recording",
    kak: "kak.normal.macro.start",
    default: "q",
    category: "history",
  },
  {
    id: "dance.history.recording.stop",
    title: "Stop recording",
    kak: "kak.normal.macro.stop",
    default: "q",
    category: "history",
  },
  {
    id: "dance.history.redo",
    title: "Redo",
    kak: "kak.normal.history.redo",
    default: "U",
    category: "history",
  },
  {
    id: "dance.history.redo.selections",
    title: "Redo a change of selections",
    kak: "kak.normal.history.redo.selections",
    default: "<a-U>",
    category: "history",
  },
  {
    id: "dance.history.repeat",
    title: "Repeat last change",
    kak: "kak.normal.history.repeat",
    default: ".",
    category: "history",
  },
  {
    id: "dance.history.repeat.edit",
    title: "Repeat last edit",
    kak: "kak.normal.history.repeat.edit",
    default: ".",
    category: "history",
  },
  {
    id: "dance.history.repeat.seek",
    title: "Repeat last seek",
    kak: "kak.normal.history.repeat.seek",
    default: "<a-.>",
    category: "history",
  },
  {
    id: "dance.history.repeat.selection",
    title: "Repeat last selection change",
    category: "history",
  },
  {
    id: "dance.history.undo",
    title: "Undo",
    kak: "kak.normal.history.undo",
    default: "u",
    category: "history",
  },
  {
    id: "dance.history.undo.selections",
    title: "Undo a change of selections",
    kak: "kak.normal.history.undo.selections",
    default: "<a-u>",
    category: "history",
  },

  // ── search ──────────────────────────────────────────────────────────────
  {
    id: "dance.search",
    title: "Search",
    kak: "kak.normal.search.forward",
    default: "/",
    category: "search",
  },
  {
    id: "dance.search.backward",
    title: "Search backward",
    kak: "kak.normal.search.backward",
    default: "<a-/>",
    category: "search",
  },
  {
    id: "dance.search.backward.extend",
    title: "Search backward (extend)",
    kak: "kak.normal.search.backward.extend",
    default: "<a-?>",
    category: "search",
  },
  {
    id: "dance.search.extend",
    title: "Search (extend)",
    kak: "kak.normal.search.forward.extend",
    default: "?",
    category: "search",
  },
  {
    id: "dance.search.next",
    title: "Select next match",
    kak: "kak.normal.search.next",
    default: "n",
    category: "search",
  },
  {
    id: "dance.search.next.add",
    title: "Add next match",
    kak: "kak.normal.search.next.add",
    default: "N",
    category: "search",
  },
  {
    id: "dance.search.previous",
    title: "Select previous match",
    kak: "kak.normal.search.prev",
    default: "<a-n>",
    category: "search",
  },
  {
    id: "dance.search.previous.add",
    title: "Add previous match",
    kak: "kak.normal.search.prev.add",
    default: "<a-N>",
    category: "search",
  },
  {
    id: "dance.search.selection",
    title: "Search current selection",
    kak: "kak.normal.search.selection",
    default: "*",
    category: "search",
  },
  {
    id: "dance.search.selection.smart",
    title: "Search current selection (smart)",
    kak: "kak.normal.search.selection.smart",
    default: "<a-*>",
    category: "search",
  },

  // ── seek ────────────────────────────────────────────────────────────────
  {
    id: "dance.seek",
    title: "Select to character (excluded)",
    kak: "kak.normal.seek.t.fwd",
    default: "t",
    category: "seek",
  },
  {
    id: "dance.seek.askObject",
    title: "Select whole object",
    kak: "kak.normal.seek.object.outer",
    default: "<a-a>",
    category: "seek",
  },
  { id: "dance.seek.askObject.end", title: "Select to whole object end", category: "seek" },
  { id: "dance.seek.askObject.end.extend", title: "Extend to whole object end", category: "seek" },
  {
    id: "dance.seek.askObject.inner",
    title: "Select inner object",
    kak: "kak.normal.seek.object.inner",
    default: "<a-i>",
    category: "seek",
  },
  { id: "dance.seek.askObject.inner.end", title: "Select to inner object end", category: "seek" },
  {
    id: "dance.seek.askObject.inner.end.extend",
    title: "Extend to inner object end",
    category: "seek",
  },
  {
    id: "dance.seek.askObject.inner.start",
    title: "Select to inner object start",
    category: "seek",
  },
  {
    id: "dance.seek.askObject.inner.start.extend",
    title: "Extend to inner object start",
    category: "seek",
  },
  { id: "dance.seek.askObject.start", title: "Select to whole object start", category: "seek" },
  {
    id: "dance.seek.askObject.start.extend",
    title: "Extend to whole object start",
    category: "seek",
  },
  {
    id: "dance.seek.backward",
    title: "Select to character (excluded, backward)",
    kak: "kak.normal.seek.t.bwd",
    default: "<a-t>",
    category: "seek",
  },
  {
    id: "dance.seek.enclosing",
    title: "Select to next enclosing character",
    kak: "kak.normal.seek.match.fwd",
    default: "m",
    category: "seek",
  },
  {
    id: "dance.seek.enclosing.backward",
    title: "Select to previous enclosing character",
    kak: "kak.normal.seek.match.bwd",
    default: "<a-m>",
    category: "seek",
  },
  {
    id: "dance.seek.enclosing.extend",
    title: "Extend to next enclosing",
    kak: "kak.normal.seek.match.fwd.extend",
    default: "M",
    category: "seek",
  },
  {
    id: "dance.seek.enclosing.extend.backward",
    title: "Extend to previous enclosing",
    kak: "kak.normal.seek.match.bwd.extend",
    default: "<a-M>",
    category: "seek",
  },
  {
    id: "dance.seek.extend",
    title: "Extend to character (excluded)",
    kak: "kak.normal.seek.t.extend.fwd",
    default: "T",
    category: "seek",
  },
  {
    id: "dance.seek.extend.backward",
    title: "Extend to character (excluded, backward)",
    kak: "kak.normal.seek.t.extend.bwd",
    default: "<a-T>",
    category: "seek",
  },
  {
    id: "dance.seek.included",
    title: "Select to character (included)",
    kak: "kak.normal.seek.f.fwd",
    default: "f",
    category: "seek",
  },
  {
    id: "dance.seek.included.backward",
    title: "Select to character (included, backward)",
    kak: "kak.normal.seek.f.bwd",
    default: "<a-f>",
    category: "seek",
  },
  {
    id: "dance.seek.included.extend",
    title: "Extend to character (included)",
    kak: "kak.normal.seek.f.extend.fwd",
    default: "F",
    category: "seek",
  },
  {
    id: "dance.seek.included.extend.backward",
    title: "Extend to character (included, backward)",
    kak: "kak.normal.seek.f.extend.bwd",
    default: "<a-F>",
    category: "seek",
  },
  { id: "dance.seek.leap", title: "Leap forward", category: "seek" },
  { id: "dance.seek.leap.backward", title: "Leap backward", category: "seek" },
  { id: "dance.seek.object", title: "Select object", category: "seek" },
  {
    id: "dance.seek.syntax.child.experimental",
    title: "Select child syntax object",
    category: "seek",
  },
  { id: "dance.seek.syntax.experimental", title: "Select syntax object", category: "seek" },
  {
    id: "dance.seek.syntax.next.experimental",
    title: "Select next syntax object",
    category: "seek",
  },
  {
    id: "dance.seek.syntax.parent.experimental",
    title: "Select parent syntax object",
    category: "seek",
  },
  {
    id: "dance.seek.syntax.previous.experimental",
    title: "Select previous syntax object",
    category: "seek",
  },
  {
    id: "dance.seek.word",
    title: "Select to next word start",
    kak: "kak.normal.seek.word.next",
    default: "w",
    category: "seek",
  },
  {
    id: "dance.seek.word.backward",
    title: "Select to previous word start",
    kak: "kak.normal.seek.word.prev",
    default: "b",
    category: "seek",
  },
  {
    id: "dance.seek.word.extend",
    title: "Extend to next word start",
    kak: "kak.normal.seek.word.next.extend",
    default: "W",
    category: "seek",
  },
  {
    id: "dance.seek.word.extend.backward",
    title: "Extend to previous word start",
    kak: "kak.normal.seek.word.prev.extend",
    default: "B",
    category: "seek",
  },
  {
    id: "dance.seek.word.ws",
    title: "Select to next WORD start",
    kak: "kak.normal.seek.WORD.next",
    default: "<a-w>",
    category: "seek",
  },
  {
    id: "dance.seek.word.ws.backward",
    title: "Select to previous WORD start",
    kak: "kak.normal.seek.WORD.prev",
    default: "<a-b>",
    category: "seek",
  },
  { id: "dance.seek.word.ws.extend", title: "Extend to next WORD start", category: "seek" },
  {
    id: "dance.seek.word.ws.extend.backward",
    title: "Extend to previous WORD start",
    category: "seek",
  },
  {
    id: "dance.seek.wordEnd",
    title: "Select to next word end",
    kak: "kak.normal.seek.word.end",
    default: "e",
    category: "seek",
  },
  {
    id: "dance.seek.wordEnd.extend",
    title: "Extend to next word end",
    kak: "kak.normal.seek.word.end.extend",
    default: "E",
    category: "seek",
  },
  {
    id: "dance.seek.wordEnd.ws",
    title: "Select to next WORD end",
    kak: "kak.normal.seek.WORD.end",
    default: "<a-e>",
    category: "seek",
  },
  { id: "dance.seek.wordEnd.ws.extend", title: "Extend to next WORD end", category: "seek" },
  { id: "dance.seek.wordLabel", title: "Leap to word", category: "seek" },
  { id: "dance.seek.wordLabel.extend", title: "Leap to word (extend)", category: "seek" },

  // ── select ──────────────────────────────────────────────────────────────
  {
    id: "dance.select.buffer",
    title: "Select whole buffer",
    kak: "kak.normal.select.buffer",
    default: "%",
    category: "select",
  },
  { id: "dance.select.documentEnd.extend", title: "Extend to last character", category: "select" },
  { id: "dance.select.documentEnd.jump", title: "Jump to last character", category: "select" },
  {
    id: "dance.select.down.extend",
    title: "Extend down",
    kak: "kak.normal.select.down.extend",
    default: "J",
    category: "select",
  },
  {
    id: "dance.select.down.jump",
    title: "Jump down",
    kak: "kak.normal.select.down",
    default: "j",
    category: "select",
  },
  { id: "dance.select.firstLine.extend", title: "Extend to first line", category: "select" },
  {
    id: "dance.select.firstLine.jump",
    title: "Jump to first line",
    kak: "kak.normal.goto.firstLine",
    default: "gg",
    category: "select",
  },
  {
    id: "dance.select.firstVisibleLine",
    title: "Select to first visible line",
    kak: "kak.normal.goto.topVisible",
    default: "gt",
    category: "select",
  },
  {
    id: "dance.select.firstVisibleLine.extend",
    title: "Extend to first visible line",
    category: "select",
  },
  {
    id: "dance.select.firstVisibleLine.jump",
    title: "Jump to first visible line",
    category: "select",
  },
  { id: "dance.select.horizontally", title: "Select horizontally", category: "select" },
  {
    id: "dance.select.lastLine",
    title: "Select to last line",
    kak: "kak.normal.goto.lastLine",
    default: "ge",
    category: "select",
  },
  { id: "dance.select.lastLine.extend", title: "Extend to last line", category: "select" },
  { id: "dance.select.lastLine.jump", title: "Jump to last line", category: "select" },
  { id: "dance.select.lastVisibleLine", title: "Select to last visible line", category: "select" },
  {
    id: "dance.select.lastVisibleLine.extend",
    title: "Extend to last visible line",
    category: "select",
  },
  {
    id: "dance.select.lastVisibleLine.jump",
    title: "Jump to last visible line",
    category: "select",
  },
  {
    id: "dance.select.left.extend",
    title: "Extend left",
    kak: "kak.normal.select.left.extend",
    default: "H",
    category: "select",
  },
  {
    id: "dance.select.left.jump",
    title: "Jump left",
    kak: "kak.normal.select.left",
    default: "h",
    category: "select",
  },
  {
    id: "dance.select.line.above",
    title: "Select line above",
    kak: "kak.normal.select.line.above",
    default: "<a-K>",
    category: "select",
  },
  { id: "dance.select.line.above.extend", title: "Extend to line above", category: "select" },
  {
    id: "dance.select.line.below",
    title: "Select line below",
    kak: "kak.normal.select.line.below",
    default: "x",
    category: "select",
  },
  {
    id: "dance.select.line.below.extend",
    title: "Extend to line below",
    kak: "kak.normal.select.line.extend",
    default: "X",
    category: "select",
  },
  {
    id: "dance.select.lineEnd",
    title: "Select to line end",
    kak: "kak.normal.select.line.end",
    default: "<a-l>",
    category: "select",
  },
  { id: "dance.select.lineEnd.extend", title: "Extend to line end", category: "select" },
  {
    id: "dance.select.lineStart",
    title: "Select to line start",
    kak: "kak.normal.select.line.start",
    default: "<a-h>",
    category: "select",
  },
  { id: "dance.select.lineStart.extend", title: "Extend to line start", category: "select" },
  { id: "dance.select.lineStart.jump", title: "Jump to line start", category: "select" },
  {
    id: "dance.select.lineStart.skipBlank.extend",
    title: "Extend to line start (skip blank)",
    category: "select",
  },
  {
    id: "dance.select.lineStart.skipBlank.jump",
    title: "Jump to line start (skip blank)",
    kak: "kak.normal.goto.lineStartIndent",
    default: "gi",
    category: "select",
  },
  {
    id: "dance.select.middleVisibleLine",
    title: "Select to middle visible line",
    kak: "kak.normal.goto.middleVisible",
    default: "gc",
    category: "select",
  },
  {
    id: "dance.select.middleVisibleLine.extend",
    title: "Extend to middle visible line",
    category: "select",
  },
  {
    id: "dance.select.middleVisibleLine.jump",
    title: "Jump to middle visible line",
    category: "select",
  },
  {
    id: "dance.select.right.extend",
    title: "Extend right",
    kak: "kak.normal.select.right.extend",
    default: "L",
    category: "select",
  },
  {
    id: "dance.select.right.jump",
    title: "Jump right",
    kak: "kak.normal.select.right",
    default: "l",
    category: "select",
  },
  { id: "dance.select.to", title: "Select to (line)", category: "select" },
  { id: "dance.select.to.extend", title: "Extend to", category: "select" },
  {
    id: "dance.select.to.jump",
    title: "Go to",
    kak: "kak.normal.goto",
    default: "g",
    category: "select",
  },
  {
    id: "dance.select.up.extend",
    title: "Extend up",
    kak: "kak.normal.select.up.extend",
    default: "K",
    category: "select",
  },
  {
    id: "dance.select.up.jump",
    title: "Jump up",
    kak: "kak.normal.select.up",
    default: "k",
    category: "select",
  },
  { id: "dance.select.vertically", title: "Select vertically", category: "select" },

  // ── selections ──────────────────────────────────────────────────────────
  {
    id: "dance.selections.changeDirection",
    title: "Change direction of selections",
    kak: "kak.normal.selections.flipDirection",
    default: "<a-;>",
    category: "selections",
  },
  { id: "dance.selections.changeOrder", title: "Reverse selections order", category: "selections" },
  {
    id: "dance.selections.clear.main",
    title: "Clear main selection",
    kak: "kak.normal.selections.removeMain",
    default: "<a-,>",
    category: "selections",
  },
  {
    id: "dance.selections.clear.secondary",
    title: "Clear all secondary selections",
    kak: "kak.normal.selections.keepMain",
    default: ",",
    category: "selections",
  },
  {
    id: "dance.selections.copy",
    title: "Copy selections below",
    kak: "kak.normal.selections.copy.below",
    default: "C",
    category: "selections",
  },
  {
    id: "dance.selections.copy.above",
    title: "Copy selections above",
    kak: "kak.normal.selections.copy.above",
    default: "<a-C>",
    category: "selections",
  },
  {
    id: "dance.selections.expandToLines",
    title: "Expand to whole lines",
    kak: "kak.normal.selections.expand",
    default: "x",
    category: "selections",
  },
  {
    id: "dance.selections.faceBackward",
    title: "Backward selections",
    kak: "kak.normal.selections.faceBackward",
    default: "<a-;>",
    category: "selections",
  },
  {
    id: "dance.selections.faceForward",
    title: "Forward selections",
    kak: "kak.normal.selections.faceForward",
    default: "<a-:>",
    category: "selections",
  },
  { id: "dance.selections.filter", title: "Filter selections", category: "selections" },
  {
    id: "dance.selections.filter.regexp",
    title: "Keep selections matching regex",
    kak: "kak.normal.selections.filterKeep",
    default: "<a-k>",
    category: "selections",
  },
  {
    id: "dance.selections.filter.regexp.inverse",
    title: "Drop selections matching regex",
    kak: "kak.normal.selections.filterDrop",
    default: "<a-K>",
    category: "selections",
  },
  { id: "dance.selections.hideIndices", title: "Hide selection indices", category: "selections" },
  {
    id: "dance.selections.merge",
    title: "Merge contiguous selections",
    kak: "kak.normal.selections.merge",
    default: "<a-_>",
    category: "selections",
  },
  { id: "dance.selections.open", title: "Open selected file", category: "selections" },
  {
    id: "dance.selections.orderAscending",
    title: "Order selections ascending",
    category: "selections",
  },
  {
    id: "dance.selections.orderDescending",
    title: "Order selections descending",
    category: "selections",
  },
  {
    id: "dance.selections.pipe",
    title: "Pipe selections (insert command output)",
    kak: "kak.normal.selections.pipe.insert",
    default: "!",
    category: "selections",
  },
  {
    id: "dance.selections.pipe.append",
    title: "Pipe and append output after",
    kak: "kak.normal.selections.pipe.append",
    default: "<a-!>",
    category: "selections",
  },
  {
    id: "dance.selections.pipe.prepend",
    title: "Pipe and prepend output before",
    category: "selections",
  },
  {
    id: "dance.selections.pipe.replace",
    title: "Pipe and replace selection",
    kak: "kak.normal.selections.pipe.replace",
    default: "|",
    category: "selections",
  },
  {
    id: "dance.selections.reduce",
    title: "Reduce selections to their cursor",
    kak: "kak.normal.selections.reduce",
    default: ";",
    category: "selections",
  },
  {
    id: "dance.selections.reduce.edges",
    title: "Reduce selections to their ends",
    category: "selections",
  },
  {
    id: "dance.selections.restore",
    title: "Restore selections from register",
    kak: "kak.normal.selections.restore",
    default: "z",
    category: "selections",
  },
  {
    id: "dance.selections.restore.withCurrent",
    title: "Combine register selections with current",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.both",
    title: "Rotate selections clockwise (both)",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.both.reverse",
    title: "Rotate selections counter-clockwise (both)",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.contents",
    title: "Rotate selection contents clockwise",
    kak: "kak.normal.selections.rotate.contents",
    default: "<a-)>",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.contents.reverse",
    title: "Rotate selection contents counter-clockwise",
    kak: "kak.normal.selections.rotate.contents.reverse",
    default: "<a-(>",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.selections",
    title: "Rotate selections clockwise",
    kak: "kak.normal.selections.rotate",
    default: ")",
    category: "selections",
  },
  {
    id: "dance.selections.rotate.selections.reverse",
    title: "Rotate selections counter-clockwise",
    kak: "kak.normal.selections.rotate.reverse",
    default: "(",
    category: "selections",
  },
  {
    id: "dance.selections.save",
    title: "Save selections to register",
    kak: "kak.normal.selections.save",
    default: "Z",
    category: "selections",
  },
  {
    id: "dance.selections.saveText",
    title: "Copy selection text",
    kak: "kak.normal.selections.yank",
    default: "y",
    category: "selections",
  },
  {
    id: "dance.selections.select",
    title: "Select within selections (regex)",
    kak: "kak.normal.selections.select.regex",
    default: "s",
    category: "selections",
  },
  {
    id: "dance.selections.select.orLeap",
    title: "Select within (or leap)",
    category: "selections",
  },
  { id: "dance.selections.showIndices", title: "Show selection indices", category: "selections" },
  { id: "dance.selections.sort", title: "Sort selections", category: "selections" },
  {
    id: "dance.selections.split",
    title: "Split selections by regex",
    kak: "kak.normal.selections.split.regex",
    default: "S",
    category: "selections",
  },
  {
    id: "dance.selections.splitLines",
    title: "Split selections at line boundaries",
    kak: "kak.normal.selections.split.lines",
    default: "<a-s>",
    category: "selections",
  },
  {
    id: "dance.selections.splitLines.orLeap.backward",
    title: "Split-lines or leap backward",
    category: "selections",
  },
  {
    id: "dance.selections.toggleIndices",
    title: "Toggle selection indices",
    category: "selections",
  },
  {
    id: "dance.selections.trimLines",
    title: "Trim partial lines off selection",
    kak: "kak.normal.selections.trim.lines",
    default: "<a-x>",
    category: "selections",
  },
  {
    id: "dance.selections.trimWhitespace",
    title: "Trim whitespace from selections",
    kak: "kak.normal.selections.trim.whitespace",
    default: "_",
    category: "selections",
  },

  // ── view ────────────────────────────────────────────────────────────────
  {
    id: "dance.view.line",
    title: "Reveal a position based on the main cursor",
    kak: "kak.normal.view.line",
    default: "v",
    category: "view",
  },

  // ── dev ─────────────────────────────────────────────────────────────────
  {
    id: "dance.dev.copyLastErrorMessage",
    title: "Copies the last encountered error message",
    category: "dev",
  },
  {
    id: "dance.dev.setSelectionBehavior",
    title: "Set the selection behavior of the specified mode",
    category: "dev",
  },
  { id: "dance.keybindings.setup", title: "Set up Dance keybindings", category: "dev" },
] as const;

export const DANCE_BY_ID: ReadonlyMap<string, DanceCommand> = new Map(
  DANCE_COMMANDS.map((c) => [c.id, c]),
);

export function getDanceCommand(id: string): DanceCommand | undefined {
  return DANCE_BY_ID.get(id);
}

export function isDanceCommandId(id: string): boolean {
  return DANCE_BY_ID.has(id) || id.startsWith("dance.");
}
